name: ${PROJECT_NAME}

services:
  o-vpn:
    image: openvpn/openvpn-as:latest
    container_name: o-vpn-container
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    ports:
      - "127.0.0.1:${OPENVPN_ADMIN_PORT}:943"
      - "${OPENVPN_TCP_PORT}:${OPENVPN_TCP_PORT}/tcp"
      - "${OPENVPN_UDP_PORT}:${OPENVPN_UDP_PORT}/udp"
    volumes:
      - ${OPENVPN_VOLUME}:/openvpn
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true
