name: ${PROJECT_NAME}

services:
  x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: x-ui-container
    restart: unless-stopped
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: ${XUI_ENABLE_FAIL2BAN}
      XUI_INIT_WEB_BASE_PATH: ${XUI_WEB_BASE_PATH}
      XUI_PORT: ${XUI_INTERNAL_PORT}
    ports:
      - "127.0.0.1:${XUI_PANEL_PORT}:${XUI_INTERNAL_PORT}"
      - "${XRAY_REALITY_PORT}:${XRAY_REALITY_PORT}/tcp"
    volumes:
      - ${XUI_DATA_VOLUME}:/etc/x-ui
      - ${XUI_CERT_VOLUME}:/root/cert
      - ${XUI_ACME_VOLUME}:/root/.acme.sh
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true
