name: ${PROJECT_NAME}

services:
  registry:
    image: registry:2
    container_name: registry-container
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REGISTRY_PORT}:5000"
    volumes:
      - ${VOLUME}:/var/lib/registry
      - ./auth:/auth:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: ${AUTH_PATH}
      REGISTRY_AUTH_HTPASSWD_REALM: ${REGISTRY_AUTH_REALM}
      REGISTRY_STORAGE_DELETE_ENABLED: "${REGISTRY_STORAGE_DELETE_ENABLED}"
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true
