name: vennro

services:
  PhpMyAdmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin-container
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb-container
    volumes:
      - ./docker/server/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      - proxy

networks:
  proxy:
    external: true
