name: ${PROJECT_NAME}

services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone-container
    environment:
      RCLONE_CONFIG: /config/rclone/rclone.conf
    volumes:
      - ./config:/config/rclone
      - ./archives:/archives:ro
