name: ${PROJECT_NAME}

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-container
    restart: unless-stopped
    environment:
      PUID: ${NPM_PUID}
      PGID: ${NPM_PGID}
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:${NPM_PORT}:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true
