name: ${PROJECT_NAME}

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-container
    restart: unless-stopped
    volumes:
      - volume-name:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-name

volumes:
  volume-name:
    name: ${VOLUME}

networks:
  network-name:
    name: ${NETWORK}
    external: true