name: ${PROJECT_NAME}

services:
  xray:
    image: ${XRAY_IMAGE}
    container_name: ${XRAY_CONTAINER}
    restart: unless-stopped
    command: run -config /etc/xray/config.json
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    ports:
      - "${XRAY_BIND_IP}:${XRAY_PORT}:${XRAY_PORT}/tcp"
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true
