name: ${PROJECT_NAME}

services:
  xray:
    image: teddysun/xray:latest
    container_name: xray-container
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    ports:
      - "443:443"
    networks:
      - network-name

networks:
  network-name:
    name: ${NETWORK}
    external: true