name: ${PROJECT_NAME}

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - volume-name:/var/lib/postgresql
    networks:
      - network-name

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - network-name

volumes:
  volume-name:
    name: ${VOLUME}

networks:
  network-name:
    name: ${NETWORK}
    external: true
