name: vennro

services:
  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - proxy

networks:
  proxy:
    external: true